pub const R2D2_TELEGRAM_BOT_TOKEN: &str = "7756023892:AAGUdUuN42khVQCIjZVKbbMROXOweyOZ3e4";

pub const CHAT_MONEY_PRINTER: &str = "7140202875";
pub const CHAT_MONEY_PRINTER_THREAD_ERROR_REPORT: &str = "";
pub const CHAT_MONEY_PRINTER_THREAD_WALLET_WATCHER: &str = "";

pub const CHAT_MONEY_PRINTER_THREAD_TEST: &str = "";

pub const BIG_DICK_BOY_CHAT_ID: &str = "7140202875";
